# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('addons', ['core','applications','mobility'])
    module.source = [
        'model/addons.cc',
        'model/myonoff.cc',
        'model/mypktsink.cc',
        'model/mytag.cc',
        'model/statistics.cc',
        'helper/addons-helper.cc',
        'helper/mypktsinkhelper.cc',
        'helper/myonoffhelper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('addons')
    module_test.source = [
        'test/addons-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/addons-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'addons'
    headers.source = [
        'model/addons.h',
        'model/myonoff.h',
        'model/mytag.h',
        'model/statistics.h',
        'model/mypktsink.h',
        'helper/addons-helper.h',
        'helper/mypktsinkhelper.h',
        'helper/myonoffhelper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

